; ----------------------------------------
;     CapsLock to Ctrl Rebinding Script
;  by Max Pereira | github.com/maxpereira
;    Rebinds CapsLock to Ctrl w/ options
; ----------------------------------------

; ----------------------- BEGIN AUTOGENERATED CODE BLOCK WITH NEW AHK SCRIPT
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
; ----------------------- END AUTOGENERATED CODE BLOCK WITH NEW AHK SCRIPT

; -------------------------------------------
; UNCOMMENT TO ENABLE ANY OF THE FOLLOWING

; Win+CapsLock to toggle CapsLock
; #CapsLock::CapsLock

; Shift+CapsLock to toggle CapsLock
; +CapsLock::CapsLock

; Alt+CapsLock to toggle CapsLock
; !CapsLock::CapsLock

; Win+CapsLock to sleep PC
; #CapsLock::DllCall("PowrProf\SetSuspendState", "int", 0, "int", 0, "int", 0)
; -------------------------------------------

; Rebinds CapsLock to Ctrl
CapsLock::Ctrl